In [1]:
# Load library
import numpy as np

In [2]:
# Create matrix
matrix_a = np.array([[1, 1],
[1, 2]])

In [3]:
# Create matrix
matrix_b = np.array([[1, 3],
[1, 2]])

In [4]:
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [5]:
# Multiply two matrices
matrix_a @ matrix_b
np.array([[2, 5],
[3, 7]])

array([[2, 5],
       [3, 7]])

In [6]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])